development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bizdiary_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bizdiary_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: thebusinessdiary_production
  pool: 5
  username: thebusinessdiary
  password: yfhA=8
  socket: /var/run/mysqld/mysqld.sock
    
cucumber:
  <<: *test