topics:
  'Finance': 'Finance'
  'Workforce': 'Workforce'
  'Marketing': 'Marketing'
  'Operations': 'Operations'
  'Sales / Lead Conversion': 'Sales / Lead Conversion'
  'Legal': 'Legal'
  'Planning / Business Development': 'Planning / Business Development'
  'Starting up': 'Starting up'
  'Internet / Online': 'Internet / Online'
  'Job Hunting': 'Job Hunting'
  'Personal Growth': 'Personal Growth'
types:
  'Conference/Trade Show': 'Conference/Trade Show'
  'Seminar': 'Seminar'
  'Training Course': 'Training Course'
  'Networking': 'Networking'
  'Workshop': 'Workshop'
industries:
  'Agriculture': 'Agriculture'
  'Communication': 'Communication'
  'Design': 'Design'
  'Energy': 'Energy'
  'Engineering': 'Engineering'
  'Fashion & textiles': 'Fashion & textiles'
  'Finance and accounting': 'Finance and accounting'
  'Food': 'Food'
  'Hospitality and Tourism': 'Hospitality and Tourism'
  'HR and training': 'HR and training'
  'Humanities and sociocultural': 'Humanities and sociocultural'
  'IT / Technology': 'IT / Technology'
  'Languages': 'Languages'
  'Law & Justice': 'Law & Justice'
  'Management': 'Management'
  'Manufacturing': 'Manufacturing'
  'Marketing': 'Marketing'
  'Media & Film': 'Media & Film'
  'Medical': 'Medical'
  'Performing arts': 'Performing arts'
  'Personal Growth': 'Personal Growth'
  'Purchasing, logistics and transport': 'Purchasing, logistics and transport'
  'Quality, R & D and innovation': 'Quality, R & D and innovation'
  'Real estate and construction': 'Real estate and construction'
  'Sales': 'Sales'
  'Science': 'Science'
  'Security and military': 'Security and military'
  'Sports and Recreation': 'Sports and Recreation'