topics:
  'Finance': 'Finance'
  'Workforce': 'Workforce'
  'Marketing': 'Marketing'
  'Operations': 'Operations'
  'Sales / Lead Conversion': 'Sales'
  'Legal': 'Legal'
  'Planning / Business Development': 'Planning'
  'Starting up': 'Starting up'
  'Internet / Online': 'Internet'
  'Job Hunting': 'Job'
  'Personal Growth': 'Personal'
types:
  'Conference/Trade Show': 'Conference'
  'Seminar': 'Seminar'
  'Training Course': 'Training Course'
  'Networking': 'Networking'
  'Workshop': 'Workshop'
industries:
  'Agriculture': 'Agriculture'
  'Communication': 'Communication'
  'Design': 'Design'
  'Energy': 'Energy'
  'Engineering': 'Engineering'
  'Fashion & textiles': 'Fashion'
  'Finance and accounting': 'Finance'
  'Food': 'Food'
  'Hospitality and Tourism': 'Hospitality'
  'HR and training': 'HR'
  'Humanities and sociocultural': 'Humanities'
  'IT / Technology': 'IT'
  'Languages': 'Languages'
  'Law & Justice': 'Law'
  'Management': 'Management'
  'Manufacturing': 'Manufacturing'
  'Marketing': 'Marketing'
  'Media & Film': 'Media'
  'Medical': 'Medical'
  'Performing arts': 'Performing'
  'Personal Growth': 'Personal'
  'Purchasing, logistics and transport': 'Purchasing'
  'Quality, R & D and innovation': 'Quality'
  'Real estate and construction': 'Real-estate'
  'Sales': 'Sales'
  'Science': 'Science'
  'Security and military': 'Security'
  'Sports and Recreation': 'Recreation'